import type { Store, Product } from "./Grocery";

export const STORES: Store[] = [
  {
    id: 'walmart',
    name: 'Walmart',
    tagline: 'Save Money. Live Better.',
    initial: 'W',
    categories: [
      { id: 'produce',   icon: '🥦', name: 'Fresh Produce',    count: 48 },
      { id: 'protein',   icon: '🥩', name: 'Meat & Protein',   count: 32 },
      { id: 'dairy',     icon: '🥛', name: 'Dairy & Eggs',     count: 27 },
      { id: 'bakery',    icon: '🍞', name: 'Bakery',           count: 19 },
      { id: 'frozen',    icon: '🧊', name: 'Frozen Foods',     count: 55 },
      { id: 'snacks',    icon: '🍿', name: 'Snacks',           count: 63 },
      { id: 'beverages', icon: '🧃', name: 'Beverages',        count: 41 },
      { id: 'pantry',    icon: '🫙', name: 'Pantry & Canned',  count: 72 },
    ],
  },
  {
    id: 'nofrills',
    name: 'No Frills',
    tagline: "You get what you pay for, and nothing else.",
    initial: 'NF',
    categories: [
      { id: 'produce', icon: '🥦', name: 'Fresh Produce',   count: 35 },
      { id: 'protein', icon: '🥩', name: 'Meat & Protein',  count: 22 },
      { id: 'dairy',   icon: '🥛', name: 'Dairy & Eggs',    count: 18 },
      { id: 'bakery',  icon: '🍞', name: 'Bakery',          count: 12 },
      { id: 'frozen',  icon: '🧊', name: 'Frozen Foods',    count: 38 },
      { id: 'pantry',  icon: '🫙', name: 'Pantry & Canned', count: 58 },
    ],
  },
  {
    id: 'costco',
    name: 'Costco',
    tagline: 'Bulk value, every visit.',
    initial: 'C',
    categories: [
      { id: 'produce',   icon: '🥦', name: 'Fresh Produce',     count: 29 },
      { id: 'protein',   icon: '🥩', name: 'Meat & Protein',    count: 41 },
      { id: 'dairy',     icon: '🥛', name: 'Dairy & Eggs',      count: 24 },
      { id: 'bakery',    icon: '🍞', name: 'Bakery',            count: 16 },
      { id: 'frozen',    icon: '🧊', name: 'Frozen Foods',      count: 67 },
      { id: 'snacks',    icon: '🍿', name: 'Snacks',            count: 44 },
      { id: 'organic',   icon: '🌿', name: 'Organic',           count: 31 },
      { id: 'beverages', icon: '🧃', name: 'Beverages',         count: 28 },
    ],
  },
  {
    id: 'freshco',
    name: 'FreshCo',
    tagline: 'Fresh finds, smart savings.',
    initial: 'FC',
    categories: [
      { id: 'produce',       icon: '🥦', name: 'Fresh Produce',  count: 52 },
      { id: 'protein',       icon: '🥩', name: 'Meat & Protein', count: 28 },
      { id: 'dairy',         icon: '🥛', name: 'Dairy & Eggs',   count: 21 },
      { id: 'international', icon: '🌏', name: 'International',  count: 87 },
      { id: 'frozen',        icon: '🧊', name: 'Frozen Foods',   count: 45 },
      { id: 'pantry',        icon: '🫙', name: 'Pantry & Canned',count: 61 },
    ],
  },
  {
    id: 'sobeys',
    name: 'Sobeys',
    tagline: 'Better food, better life.',
    initial: 'S',
    categories: [
      { id: 'produce',   icon: '🥦', name: 'Fresh Produce',      count: 44 },
      { id: 'protein',   icon: '🥩', name: 'Meat & Protein',     count: 36 },
      { id: 'dairy',     icon: '🥛', name: 'Dairy & Eggs',       count: 25 },
      { id: 'bakery',    icon: '🍞', name: 'Bakery & Deli',      count: 23 },
      { id: 'frozen',    icon: '🧊', name: 'Frozen Foods',       count: 50 },
      { id: 'organic',   icon: '🌿', name: 'Organic & Natural',  count: 39 },
      { id: 'snacks',    icon: '🍿', name: 'Snacks & Chips',     count: 47 },
      { id: 'beverages', icon: '🧃', name: 'Beverages',          count: 33 },
    ],
  },
];

export const SAMPLE_PRODUCTS: Record<string, Product[]> = {
  produce: [
    { id: 'p1', name: 'Organic Baby Spinach 142g', price: '$3.99', unit: '/bag',   emoji: '🥬', tag: 'Organic'    },
    { id: 'p2', name: 'Roma Tomatoes',             price: '$1.49', unit: '/lb',    emoji: '🍅', tag: 'Sale'       },
    { id: 'p3', name: 'Broccoli Crown',            price: '$2.29', unit: '/each',  emoji: '🥦', tag: null         },
    { id: 'p4', name: 'Gala Apples Bag 3lb',       price: '$4.99', unit: '/bag',   emoji: '🍎', tag: 'Value Pack' },
    { id: 'p5', name: 'Yellow Onions 3lb',         price: '$2.99', unit: '/bag',   emoji: '🧅', tag: null         },
    { id: 'p6', name: 'Navel Oranges',             price: '$0.79', unit: '/each',  emoji: '🍊', tag: null         },
  ],
  protein: [
    { id: 'pr1', name: 'Chicken Breast Boneless 1kg', price: '$11.99', unit: '/kg',    emoji: '🍗', tag: 'Sale'        },
    { id: 'pr2', name: 'Extra Lean Ground Beef',      price: '$7.99',  unit: '/lb',    emoji: '🥩', tag: null          },
    { id: 'pr3', name: 'Atlantic Salmon Fillet',      price: '$14.99', unit: '/lb',    emoji: '🐟', tag: 'Fresh'       },
    { id: 'pr4', name: 'Pork Tenderloin',             price: '$9.49',  unit: '/lb',    emoji: '🥩', tag: null          },
    { id: 'pr5', name: 'Large Eggs 12pk',             price: '$4.49',  unit: '/dozen', emoji: '🥚', tag: null          },
    { id: 'pr6', name: 'Extra Firm Tofu 454g',        price: '$2.99',  unit: '/pkg',   emoji: '🫙', tag: 'Plant-based' },
  ],
  dairy: [
    { id: 'd1', name: 'Homo Milk 4L',           price: '$5.99', unit: '/jug',   emoji: '🥛', tag: null          },
    { id: 'd2', name: 'Greek Yogurt 750g',       price: '$4.49', unit: '/tub',   emoji: '🥛', tag: 'High Protein' },
    { id: 'd3', name: 'Old Cheddar Block 400g',  price: '$6.99', unit: '/block', emoji: '🧀', tag: null          },
    { id: 'd4', name: 'Salted Butter 454g',      price: '$5.79', unit: '/block', emoji: '🧈', tag: null          },
    { id: 'd5', name: 'Sour Cream 500ml',        price: '$3.29', unit: '/tub',   emoji: '🥛', tag: null          },
    { id: 'd6', name: 'Mozzarella Shredded 320g',price: '$5.49', unit: '/bag',   emoji: '🧀', tag: 'Sale'        },
  ],
  bakery: [
    { id: 'b1', name: '100% Whole Wheat Bread', price: '$3.49', unit: '/loaf', emoji: '🍞', tag: null          },
    { id: 'b2', name: 'Croissants 6pk',         price: '$4.99', unit: '/pack', emoji: '🥐', tag: 'Freshly Baked'},
    { id: 'b3', name: 'Everything Bagels 6pk',  price: '$3.99', unit: '/pack', emoji: '🥯', tag: null          },
    { id: 'b4', name: 'Banana Muffins 4pk',     price: '$5.49', unit: '/pack', emoji: '🧁', tag: 'In Store'    },
  ],
  frozen: [
    { id: 'fr1', name: 'PC Blue Menu Stir Fry Mix',   price: '$4.99', unit: '/bag',  emoji: '🧊', tag: null   },
    { id: 'fr2', name: 'Frozen Edamame 500g',          price: '$3.49', unit: '/bag',  emoji: '🫛', tag: null   },
    { id: 'fr3', name: 'Delissio Pizza Pepperoni',     price: '$7.99', unit: '/each', emoji: '🍕', tag: 'Sale' },
    { id: 'fr4', name: 'Häagen-Dazs Vanilla 500ml',   price: '$6.99', unit: '/tub',  emoji: '🍨', tag: null   },
    { id: 'fr5', name: 'Fish Sticks 600g',             price: '$8.49', unit: '/box',  emoji: '🐟', tag: null   },
    { id: 'fr6', name: 'Frozen Mango Chunks 600g',     price: '$4.49', unit: '/bag',  emoji: '🥭', tag: null   },
  ],
  snacks: [
    { id: 'sn1', name: "Lay's Classic Chips 220g",    price: '$4.49',  unit: '/bag', emoji: '🍟', tag: 'Sale' },
    { id: 'sn2', name: 'Oreo Original 500g',          price: '$5.99',  unit: '/box', emoji: '🍪', tag: null   },
    { id: 'sn3', name: 'Planters Mixed Nuts 750g',    price: '$11.99', unit: '/jar', emoji: '🥜', tag: null   },
    { id: 'sn4', name: 'Quaker Oat Bars 6pk',         price: '$4.79',  unit: '/pack',emoji: '🍫', tag: null   },
    { id: 'sn5', name: 'Smartfood White Cheddar',     price: '$3.99',  unit: '/bag', emoji: '🍿', tag: 'Fave' },
    { id: 'sn6', name: 'Nature Valley Granola 8pk',   price: '$5.49',  unit: '/box', emoji: '🌾', tag: null   },
  ],
  beverages: [
    { id: 'bv1', name: 'Tropicana OJ No Pulp 1.75L', price: '$5.49', unit: '/jug',  emoji: '🍊', tag: null          },
    { id: 'bv2', name: 'Coca-Cola 12pk Cans',         price: '$6.99', unit: '/pack', emoji: '🥤', tag: 'Sale'        },
    { id: 'bv3', name: 'Sparkling Water 12pk',        price: '$5.99', unit: '/case', emoji: '💧', tag: null          },
    { id: 'bv4', name: 'Oat Milk Barista 1L',         price: '$4.99', unit: '/carton',emoji: '🥛',tag: 'Plant-based' },
  ],
  pantry: [
    { id: 'pa1', name: 'PC Chicken Broth 900ml',         price: '$2.99',  unit: '/carton', emoji: '🫙', tag: null    },
    { id: 'pa2', name: 'Penne Pasta 900g',               price: '$2.49',  unit: '/box',    emoji: '🍝', tag: 'Value' },
    { id: 'pa3', name: 'Kirkland Olive Oil 3L',          price: '$19.99', unit: '/jug',    emoji: '🫒', tag: null    },
    { id: 'pa4', name: 'San Marzano Crushed Tomatoes',   price: '$3.79',  unit: '/can',    emoji: '🍅', tag: null    },
    { id: 'pa5', name: 'Basmati Rice 10lb',              price: '$12.99', unit: '/bag',    emoji: '🍚', tag: null    },
    { id: 'pa6', name: 'Black Beans 540ml',              price: '$1.49',  unit: '/can',    emoji: '🫘', tag: 'Sale'  },
  ],
  organic: [
    { id: 'or1', name: 'Organic Free-Range Eggs 12pk', price: '$6.99', unit: '/dozen',  emoji: '🥚', tag: 'Organic' },
    { id: 'or2', name: 'Organic Whole Milk 2L',        price: '$5.49', unit: '/jug',    emoji: '🥛', tag: 'Organic' },
    { id: 'or3', name: 'Organic Quinoa 1kg',           price: '$8.99', unit: '/bag',    emoji: '🌾', tag: 'Organic' },
    { id: 'or4', name: 'Organic Mixed Greens 142g',    price: '$4.99', unit: '/bag',    emoji: '🥬', tag: 'Organic' },
  ],
  international: [
    { id: 'in1', name: 'Jasmine Rice 10kg',      price: '$16.99', unit: '/bag',    emoji: '🍚', tag: null    },
    { id: 'in2', name: 'Coconut Milk 400ml',     price: '$1.99',  unit: '/can',    emoji: '🥥', tag: null    },
    { id: 'in3', name: 'Fish Sauce 725ml',       price: '$4.49',  unit: '/bottle', emoji: '🫙', tag: null    },
    { id: 'in4', name: 'Naan Bread 9pk',         price: '$3.99',  unit: '/pack',   emoji: '🫓', tag: 'Fresh' },
    { id: 'in5', name: 'Sriracha Hot Sauce 435ml',price: '$5.99', unit: '/bottle', emoji: '🌶️', tag: null   },
    { id: 'in6', name: 'Sesame Oil 250ml',       price: '$4.29',  unit: '/bottle', emoji: '🫙', tag: null    },
    { id: 'in7', name: 'Udon Noodles 200g',      price: '$1.99',  unit: '/pack',   emoji: '🍜', tag: 'Sale'  },
    { id: 'in8', name: 'Kimchi 400g',            price: '$5.99',  unit: '/jar',    emoji: '🥢', tag: null    },
  ],
};

export const STORE_THEME: Record<string, { dot: string; badge: string; border: string }> = {
  walmart:  { dot: 'bg-blue-950 text-blue-400',    badge: 'bg-blue-950 text-blue-400',    border: 'border-blue-800'   },
  nofrills: { dot: 'bg-orange-950 text-orange-400',badge: 'bg-orange-950 text-orange-400',border: 'border-orange-800' },
  costco:   { dot: 'bg-purple-950 text-purple-400',badge: 'bg-purple-950 text-purple-400',border: 'border-purple-800' },
  freshco:  { dot: 'bg-teal-950 text-teal-400',    badge: 'bg-teal-950 text-teal-400',    border: 'border-teal-800'   },
  sobeys:   { dot: 'bg-red-950 text-red-400',      badge: 'bg-red-950 text-red-400',      border: 'border-red-800'    },
};